export const ActionType = {
    ADD_AND_DELETE_PRODUCT_IN_CART: "ADD_AND_DELETE_PRODUCT_IN_CART",
    GET_CART: 'GET_CART',
    GET_FROM_LC: "GET_FROM_LC",
    DEC_FROM_CART: 'DEC_FROM_CART',
    GET_CART_INFO: "GET_CART_INFO",
    //--------
    ADD_TO_CARD: "ADD_TO_CARD",
    DELETE_FROM_CARD: "DELETE_FROM_CARD",
}